<?php

namespace Database\Factories;

use App\Actions\Orders\RecalculateOrderTotals;
use App\Enums\OrderStatus;
use App\Enums\OrderType;
use App\Models\Client;
use App\Models\Order;
use App\Models\OrderItem;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Order>
 */
class OrderFactory extends Factory
{
    /**
     * The order number is generated by the model when left empty.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'client_id' => Client::factory(),
            'owner_id' => User::factory()->salesExecutive(),
            'closer_id' => null,
            'team_id' => null,
            'platform_account_id' => null,
            'parent_order_id' => null,
            'type' => OrderType::Fresh,
            'status' => OrderStatus::PendingPayment,
            'currency' => 'USD',
            'subtotal_cents' => 0,
            'discount_cents' => 0,
            'total_cents' => 0,
            'ordered_on' => fake()->dateTimeBetween('-6 months', 'now')->format('Y-m-d'),
            'delivered_at' => null,
            'notes' => null,
        ];
    }

    public function upsell(): static
    {
        return $this->state(fn (array $attributes) => [
            'type' => OrderType::Upsell,
            'parent_order_id' => Order::factory(),
        ]);
    }

    public function status(OrderStatus $status): static
    {
        return $this->state(fn (array $attributes) => ['status' => $status]);
    }

    /**
     * Create line items after the order and recompute its stored totals.
     */
    public function withItems(int $count = 2): static
    {
        return $this->afterCreating(function (Order $order) use ($count): void {
            OrderItem::factory()->count($count)->create(['order_id' => $order->id]);
            app(RecalculateOrderTotals::class)->handle($order);
        });
    }
}
